# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-11 11:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('ip', models.GenericIPAddressField(db_index=True, default='', verbose_name='客户端IP')),
                ('is_deny', models.BooleanField(choices=[(1, '黑名单'), (2, '白名单')], default=1, verbose_name='黑白名单')),
            ],
        ),
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conf_key', models.CharField(default='', max_length=50, unique=True, verbose_name='配置项')),
                ('conf_type', models.IntegerField(choices=[(1, 'int'), (2, 'str'), (3, 'float'), (4, 'json')], verbose_name='配置项')),
                ('conf_value', models.TextField(default='', max_length=1024, verbose_name='配置项')),
            ],
        ),
        migrations.CreateModel(
            name='ContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, verbose_name='内容类型')),
                ('max_item', models.IntegerField(default=10, verbose_name='每个爬虫最大抓取数')),
                ('expire_time', models.IntegerField(default=30, verbose_name='过期时间(天)')),
                ('active', models.BooleanField(choices=[(0, 'active'), (1, 'discard')], db_index=True, default=0, verbose_name='是否废弃')),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='抓取时间')),
                ('result', models.TextField(default='', max_length=2048, verbose_name='抓取结果')),
            ],
        ),
        migrations.CreateModel(
            name='SearchRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='搜索时间')),
                ('ip', models.GenericIPAddressField(db_index=True, default='', verbose_name='客户端IP')),
                ('content', models.CharField(max_length=50, verbose_name='搜索内容')),
                ('is_doubtful', models.BooleanField(db_index=True, default=False, verbose_name='是否可疑')),
            ],
        ),
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='', max_length=50, verbose_name='爬虫名称')),
                ('c_name', models.CharField(default='', max_length=50, verbose_name='爬虫名称')),
                ('domain', models.CharField(default='', max_length=150, verbose_name='爬虫域名')),
                ('n_start', models.IntegerField(default=0, verbose_name='起始页数')),
                ('n_end', models.IntegerField(default=0, verbose_name='终止页数')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spider_content_type', to='spider.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='SpiderTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(db_index=True, default='', max_length=50, verbose_name='爬虫关键字')),
                ('status', models.BooleanField(choices=[(0, '初始化'), (1, '抓取中'), (2, '缓存中'), (3, '已过期')], db_index=True, verbose_name='任务状态')),
                ('run_time', models.DateTimeField(auto_now_add=True, verbose_name='爬虫开始时间')),
                ('finish_time', models.DateTimeField(null=True, verbose_name='爬虫结束时间')),
                ('pid', models.IntegerField(null=True, verbose_name='pid')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_content_type', to='spider.ContentType')),
            ],
        ),
        migrations.AddField(
            model_name='items',
            name='spider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spider_id', to='spider.Spider'),
        ),
        migrations.AddField(
            model_name='items',
            name='spider_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spider_info', to='spider.SpiderTask'),
        ),
    ]
