# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-26 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ViewLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(default='', max_length=32)),
                ('last_page', models.IntegerField(default=0)),
                ('last_view', models.DateTimeField()),
            ],
        ),
    ]
