# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-26 09:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewlog',
            options={'verbose_name': 'view log', 'verbose_name_plural': 'view log'},
        ),
        migrations.AlterModelTable(
            name='viewlog',
            table='cats_view_log',
        ),
    ]
