# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-26 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_auto_20171226_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewlog',
            name='author',
        ),
    ]
