# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-26 09:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0006_remove_viewlog_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewLog',
        ),
    ]
