# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-26 09:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cats', '0008_merge_20171226_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_page', models.IntegerField(default=0)),
                ('last_view', models.DateTimeField(db_index=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username+', related_query_name='author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'view log',
                'verbose_name_plural': 'view log',
                'db_table': 'cats_view_log',
            },
        ),
    ]
