# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-29 07:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cats', '0012_auto_20171226_1821'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picstars',
            old_name='img_id',
            new_name='img',
        ),
        migrations.RemoveField(
            model_name='piccomments',
            name='img_id',
        ),
        migrations.RemoveField(
            model_name='piclikes',
            name='author',
        ),
        migrations.RemoveField(
            model_name='piclikes',
            name='img_id',
        ),
        migrations.AddField(
            model_name='catimgs',
            name='comments',
            field=models.ManyToManyField(related_name='_catimgs_comments_+', through='cats.PicComments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='catimgs',
            name='likes',
            field=models.ManyToManyField(related_name='_catimgs_likes_+', through='cats.PicLikes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='piccomments',
            name='img',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment_img', to='cats.CatImgs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piclikes',
            name='img',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='like_img', to='cats.CatImgs'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='piclikes',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='like_author', to=settings.AUTH_USER_MODEL, to_field='username'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='piccomments',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user', to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
