# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-29 09:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0013_auto_20171229_1550'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picstars',
            name='id',
        ),
        migrations.AlterField(
            model_name='picstars',
            name='img',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cats.CatImgs'),
        ),
    ]
